name: graphtoken
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - scipy
  - matplotlib
  - openai
  - rich
  - pip
  - pytest
  - ninja
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu124
    - torch>=2.9.0
    - torch_geometric>=2.7.0
    - torchmetrics
    - torchinfo
    - transformers>=4.57,<4.58
    - datasets
    - trl
    - peft
    - bitsandbytes
    - flash_attn
    - huggingface-hub<1.0
    - wandb>=0.22.3
    - streamlit
