name: graphtoken
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - scipy
  - matplotlib
  - openai
  - wandb
  - pip
  - ninja
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu124
    - torch
    - torch_geometric
    - torchmetrics
    - transformers
    - datasets
    - trl
    - peft
    - bitsandbytes
    - flash_attn
    